//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Surajit_TestEntities : DbContext
    {
        public Surajit_TestEntities()
            : base("name=Surajit_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChatMessageDetail> ChatMessageDetails { get; set; }
        public DbSet<ChatPrivateMessageDetail> ChatPrivateMessageDetails { get; set; }
        public DbSet<ChatPrivateMessageMaster> ChatPrivateMessageMasters { get; set; }
        public DbSet<ChatUserDetail> ChatUserDetails { get; set; }
    }
}
